#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Debug
DEBUG = False
# Name
NAME = 'pySMSd'
# Version
VERION = 'v0.1'

# Main files
HOME_FOLDER = ''
CONFIG_FILE = HOME_FOLDER + 'CONF_Base'
LOG_FILE = HOME_FOLDER + 'LOG.log'

# Counter for checking pySMSd
MAIN_COUNTER = 0
MAIN_INTERVAL = 5
MAIN_MINUTO = (60/MAIN_INTERVAL)
MAIN_HORA = (MAIN_MINUTO*60)


# SMSd control
SMS_CELLNUMBER_MASTER = '+55319XXXXYYYY'
SMS_CELLNUMBERS = []
SMS_ISRUNNING = False
SMS_STARTED = False
SMS_INIT_RUNNING = False
SMS_TRYAGAIN_INIT = True
SMS_USBPORT = 0
SMS_USBPORT_MAX = 4
SMS_CHECKING = False
SMS_VALIDMSG = False
SMS_SENT = False
SMS_TRYSEND_COUNT = 0
SMS_TRYSTART_COUNT = 0
SMS_LASTSMS_TIME = ''
SMS_AUTOSEND_DATE = ''
SMS_AUTOSEND_TIME = ''
SMS_TRYSTART_FLAG = 'Ok'
SMS_TRYSTART_MAX = 5
SMS_SIGNALQUALITY = 'Initializing...'
SMS_LOG = HOME_FOLDER + 'SMS.log'

SMS_SENDMSG_FLAG = False
SMS_FROM_NUM = ''
SMS_SENDMSG_CONTENT = ''

SMS_FINISHED = True




